name: Docker Image CI

on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: Bearmijos/hello-amex@v1
        with:
          who-to-greet: 'Amex Cloud!'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
#     - name: Build the Docker image
#       run: |
#         echo "${{ secrets.DOCKERPW }}" | docker login -u "bryanarmijos" --password-stdin
#         docker image build -t bryanarmijos/hello-world:v2 .
#         docker push bryanarmijos/hello-world:v2
