name: Docker Image CI

on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "bryanarmijos" --password-stdin
        docker image build -t bryanarmijos/hello-world:v1 .
        docker push bryanarmijos/hello-world:v1
